apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    app: {{ .Values.component }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      serviceAccountName: {{ .Values.component }}
      initContainers:
        - name: parameters-pull
          image: 512646826903.dkr.ecr.us-east-1.amazonaws.com/parameter-store-init-container-image:v1.0.6
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          env:
            - name: PARAMS
              value: {{ .Values.PARAMS }}
      containers:
        - name: {{ .Values.component }}
          image: 512646826903.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:v1.0.5
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
      volumes:
        - name: parameters
          emptyDir: { }