env: dev
replica: 1
PARAMS: "dev.roboshop.cart.REDIS_HOST,REDIS_HOST dev.roboshop.cart.CATALOGUE_HOST,CATALOGUE_HOST  dev.roboshop.cart.CATALOGUE_PORT,CATALOGUE_PORT"

component: cart
service:
  port: 80
  containerPort: 8080


resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "150Mi"
    cpu: "100m"