env: dev
replica: 1
PARAMS: "dev.roboshop.catalogue.MONGO_URL,MONGO_URL"

component: catalogue
schema_type: mongo
service:
  port: 80
  containerPort: 8080

job:
  enabled: true
  PARAMS: "dev.roboshop.docdb.username,DOCDB_USER dev.roboshop.docdb.password,DOCDB_PASS dev.roboshop.docdb.endpoint,DOCDB_ENDPOINT"



resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "150Mi"
    cpu: "100m"
