env: dev
replica: 1
PARAMS: "dev.roboshop.shipping.CART_ENDPOINT,CART_ENDPOINT  dev.roboshop.shipping.DB_HOST,DB_HOST"

component: shipping
schema_type: mysql
service:
  port: 80
  containerPort: 8080

job:
  enabled: true
  PARAMS: "dev.roboshop.rds.endpoint,DB_HOST dev.roboshop.rds.username,DB_USER dev.roboshop.rds.password,DB_PASS"


resources:
  enabled: true
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "2.5Gi"
    cpu: "1500m"


