env: prod
replica: 2
PARAMS: "prod.roboshop.cart.REDIS_HOST,REDIS_HOST prod.roboshop.cart.CATALOGUE_HOST,CATALOGUE_HOST  prod.roboshop.cart.CATALOGUE_PORT,CATALOGUE_PORT"

component: cart
service:
  port: 80
  containerPort: 8080


resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "150Mi"
    cpu: "100m"