env: prod
replica: 2
PARAMS: "prod.roboshop.catalogue.MONGO_URL,MONGO_URL"

component: catalogue
schema_type: mongo
service:
  port: 80
  containerPort: 8080

job:
  enabled: true
  PARAMS: "prod.roboshop.docdb.username,DOCDB_USER prod.roboshop.docdb.password,DOCDB_PASS prod.roboshop.docdb.endpoint,DOCDB_ENDPOINT"
