env: prod
replica: 2
PARAMS: "prod.roboshop.user.MONGO_URL,MONGO_URL  prod.roboshop.user.REDIS_HOST,REDIS_HOST"

component: user
service:
  port: 80
  containerPort: 8080


resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "150Mi"
    cpu: "100m"